version: '3'
volumes:
  db-data: {}
networks:
  local:
    driver: bridge
services:
  rabbitmq:
    image: rabbitmq:3.7.8-management
    networks:
      - local
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: local
    healthcheck:
      test: rabbitmq-diagnostics ping
      interval: 1s
      timeout: 2s
      retries: 30
      start_period: 3s
    ports:
      - '5672:5672'
      - '15672:15672'
  postgres:
    image: postgres:11
    networks:
      - local
    environment:
      POSTGRES_DB: taskcluster
      POSTGRES_HOST_AUTH_METHOD: trust
      LC_COLLATE: en_US.UTF8
      LC_CTYPE: en_US.UTF8
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: pg_isready -U postgres
      interval: 1s
      timeout: 2s
      retries: 30
      start_period: 3s
    ports:
      - '5432:5432'
  pg_init_db:
    image: taskcluster/taskcluster:v44.13.5
    networks:
      - local
    environment: {}
    x-info: Run this first to bring database up to date
    command:
      - script/db:upgrade
    depends_on:
      postgres:
        condition: service_healthy
  ui:
    image: taskcluster/taskcluster:v44.13.5
    networks:
      - local
    environment:
      PORT: 9009
      APPLICATION_NAME: Taskcluster
      GRAPHQL_SUBSCRIPTION_ENDPOINT: http://localhost:3050/graphql
      GRAPHQL_ENDPOINT: http://localhost:3050/graphql
      UI_LOGIN_STRATEGY_NAMES: local
    command:
      - ui/web
    ports:
      - '9009:9009'
  auth-web:
    image: taskcluster/taskcluster:v44.13.5
    networks:
      - local
    environment:
      TASKCLUSTER_ROOT_URL: http://localhost:3050
      LEVEL: debug
      PORT: 3011
      NODE_ENV: development
      FORCE_SSL: 'false'
      TRUST_PROXY: 'true'
      READ_DB_URL: postgresql://postgres@postgres:5432/taskcluster
      WRITE_DB_URL: postgresql://postgres@postgres:5432/taskcluster
      PULSE_USERNAME: admin
      PULSE_PASSWORD: admin
      PULSE_HOSTNAME: rabbitmq
      PULSE_VHOST: local
      PULSE_AMQPS: 'false'
    command:
      - auth/web
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - '3011:3011'
  github-web:
    image: taskcluster/taskcluster:v44.13.5
    networks:
      - local
    environment:
      APPLICATION_NAME: Taskcluster
      TASKCLUSTER_ROOT_URL: http://localhost:3050
      READ_DB_URL: postgresql://postgres@postgres:5432/taskcluster
      WRITE_DB_URL: postgresql://postgres@postgres:5432/taskcluster
      LEVEL: debug
      PORT: 3012
      NODE_ENV: development
      FORCE_SSL: 'false'
      TRUST_PROXY: 'true'
      PULSE_HOSTNAME: rabbitmq
      PULSE_USERNAME: admin
      PULSE_PASSWORD: admin
      PULSE_VHOST: local
      PULSE_AMQPS: 'false'
    command:
      - github/web
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - '3012:3012'
  hooks-web:
    image: taskcluster/taskcluster:v44.13.5
    networks:
      - local
    environment:
      READ_DB_URL: postgresql://postgres@postgres:5432/taskcluster
      WRITE_DB_URL: postgresql://postgres@postgres:5432/taskcluster
      TASKCLUSTER_ROOT_URL: http://localhost:3050
      LEVEL: debug
      PORT: 3013
      NODE_ENV: development
      FORCE_SSL: 'false'
      TRUST_PROXY: 'true'
      PULSE_USERNAME: admin
      PULSE_PASSWORD: admin
      PULSE_HOSTNAME: rabbitmq
      PULSE_VHOST: local
      PULSE_AMQPS: 'false'
    command:
      - hooks/web
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - '3013:3013'
  index-web:
    image: taskcluster/taskcluster:v44.13.5
    networks:
      - local
    environment:
      READ_DB_URL: postgresql://postgres@postgres:5432/taskcluster
      WRITE_DB_URL: postgresql://postgres@postgres:5432/taskcluster
      LEVEL: debug
      PORT: 3014
      NODE_ENV: development
      FORCE_SSL: 'false'
      TRUST_PROXY: 'true'
      TASKCLUSTER_ROOT_URL: http://localhost:3050
      PULSE_HOSTNAME: rabbitmq
      PULSE_USERNAME: admin
      PULSE_PASSWORD: admin
      PULSE_VHOST: local
      PULSE_AMQPS: 'false'
    command:
      - index/web
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - '3014:3014'
  notify-web:
    image: taskcluster/taskcluster:v44.13.5
    networks:
      - local
    environment:
      TASKCLUSTER_ROOT_URL: http://localhost:3050
      READ_DB_URL: postgresql://postgres@postgres:5432/taskcluster
      WRITE_DB_URL: postgresql://postgres@postgres:5432/taskcluster
      LEVEL: debug
      PORT: 3015
      NODE_ENV: development
      FORCE_SSL: 'false'
      TRUST_PROXY: 'true'
      PULSE_HOSTNAME: rabbitmq
      PULSE_USERNAME: admin
      PULSE_PASSWORD: admin
      PULSE_VHOST: local
      PULSE_AMQPS: 'false'
    command:
      - notify/web
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - '3015:3015'
  object-web:
    image: taskcluster/taskcluster:v44.13.5
    networks:
      - local
    environment:
      TASKCLUSTER_ROOT_URL: http://localhost:3050
      READ_DB_URL: postgresql://postgres@postgres:5432/taskcluster
      WRITE_DB_URL: postgresql://postgres@postgres:5432/taskcluster
      LEVEL: debug
      PORT: 3016
      NODE_ENV: development
      FORCE_SSL: 'false'
    command:
      - object/web
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - '3016:3016'
  purge-cache-web:
    image: taskcluster/taskcluster:v44.13.5
    networks:
      - local
    environment:
      LEVEL: debug
      PORT: 3017
      NODE_ENV: development
      FORCE_SSL: 'false'
      TRUST_PROXY: 'true'
      READ_DB_URL: postgresql://postgres@postgres:5432/taskcluster
      WRITE_DB_URL: postgresql://postgres@postgres:5432/taskcluster
      TASKCLUSTER_ROOT_URL: http://localhost:3050
    command:
      - purge-cache/web
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - '3017:3017'
  queue-web:
    image: taskcluster/taskcluster:v44.13.5
    networks:
      - local
    environment:
      TASKCLUSTER_ROOT_URL: http://localhost:3050
      LEVEL: debug
      PORT: 3018
      NODE_ENV: development
      FORCE_SSL: 'false'
      READ_DB_URL: postgresql://postgres@postgres:5432/taskcluster
      WRITE_DB_URL: postgresql://postgres@postgres:5432/taskcluster
      PULSE_USERNAME: admin
      PULSE_PASSWORD: admin
      PULSE_HOSTNAME: rabbitmq
      PULSE_VHOST: local
      PULSE_AMQPS: 'false'
    command:
      - queue/web
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - '3018:3018'
  secrets-web:
    image: taskcluster/taskcluster:v44.13.5
    networks:
      - local
    environment:
      TASKCLUSTER_ROOT_URL: http://localhost:3050
      READ_DB_URL: postgresql://postgres@postgres:5432/taskcluster
      WRITE_DB_URL: postgresql://postgres@postgres:5432/taskcluster
      LEVEL: debug
      PORT: 3019
      NODE_ENV: development
      FORCE_SSL: 'false'
    command:
      - secrets/web
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - '3019:3019'
  web-server-web:
    image: taskcluster/taskcluster:v44.13.5
    networks:
      - local
    environment:
      LEVEL: debug
      PORT: 3050
      TRUST_PROXY: 'true'
      TASKCLUSTER_ROOT_URL: http://localhost:3050
      READ_DB_URL: postgresql://postgres@postgres:5432/taskcluster
      WRITE_DB_URL: postgresql://postgres@postgres:5432/taskcluster
      PULSE_USERNAME: admin
      PULSE_PASSWORD: admin
      PULSE_HOSTNAME: rabbitmq
      PULSE_VHOST: local
      PULSE_AMQPS: 'false'
    command:
      - web-server/web
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - '3050:3050'
  worker-manager-web:
    image: taskcluster/taskcluster:v44.13.5
    networks:
      - local
    environment:
      LEVEL: debug
      TASKCLUSTER_ROOT_URL: http://localhost:3050
      READ_DB_URL: postgresql://postgres@postgres:5432/taskcluster
      WRITE_DB_URL: postgresql://postgres@postgres:5432/taskcluster
      PORT: 3020
      NODE_ENV: development
      FORCE_SSL: 'false'
      TRUST_PROXY: 'true'
      PULSE_HOSTNAME: rabbitmq
      PULSE_USERNAME: admin
      PULSE_PASSWORD: admin
      PULSE_VHOST: local
      PULSE_AMQPS: 'false'
    command:
      - worker-manager/web
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - '3020:3020'
